<?php

namespace srag\LibrariesNamespaceChanger;

use Closure;
use Composer\Config;
use Composer\Script\Event;
use stdClass;

/**
 * Class GeneratePluginPhpAndXml
 *
 * @package srag\LibrariesNamespaceChanger
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @internal
 */
final class GeneratePluginPhpAndXml
{

    const AUTOGENERATED_COMMENT = "Autogenerated from " . self::PLUGIN_COMPOSER_JSON . " - All changes will be overridden if generated again!";
    const LUCENE_OBJECT_DEFINITION_XML = "LuceneObjectDefinition.xml";
    const PLUGIN_COMPOSER_JSON = "composer.json";
    const PLUGIN_PHP = "plugin.php";
    const PLUGIN_XML = "plugin.xml";
    const REPOSITORY_OBJECT = "Services/Repository/RepositoryObject";
    /**
     * @var self|null
     */
    private static $instance = null;
    /**
     * @var string
     */
    private static $plugin_root = "";
    /**
     * @var Event
     */
    private $event;


    /**
     * GeneratePluginPhpAndXml constructor
     *
     * @param Event $event
     */
    private function __construct(Event $event)
    {
        $this->event = $event;
    }


    /**
     * @param Event $event
     *
     * @internal
     */
    public static function generatePluginPhpAndXml(Event $event)/*: void*/
    {
        self::$plugin_root = rtrim(Closure::bind(function () : string {
            return $this->baseDir;
        }, $event->getComposer()->getConfig(), Config::class)(), "/");

        self::getInstance($event)->doGeneratePluginPhpAndXml();
    }


    /**
     * @param Event $event
     *
     * @return self
     */
    private static function getInstance(Event $event) : self
    {
        if (self::$instance === null) {
            self::$instance = new self($event);
        }

        return self::$instance;
    }


    /**
     *
     */
    private function doGeneratePluginPhpAndXml()/*: void*/
    {
        $plugin_composer_json = json_decode(file_get_contents(self::$plugin_root . "/" . self::PLUGIN_COMPOSER_JSON));

        $plugins_vars = [
            "id"                => strval($plugin_composer_json->ilias_plugin->id),
            "version"           => strval($plugin_composer_json->version),
            "ilias_min_version" => strval($plugin_composer_json->ilias_plugin->ilias_min_version),
            "ilias_max_version" => strval($plugin_composer_json->ilias_plugin->ilias_max_version),
            "responsible"       => strval($plugin_composer_json->authors[0]->name),
            "responsible_mail"  => strval($plugin_composer_json->authors[0]->email)
        ];
        if (!empty($plugin_composer_json->ilias_plugin->learning_progress)) {
            $plugins_vars["learning_progress"] = true;
        }
        if (!empty($plugin_composer_json->ilias_plugin->supports_export)) {
            $plugins_vars["supports_export"] = true;
        }

        file_put_contents(self::$plugin_root . "/" . self::PLUGIN_PHP, '<?php
// ' . self::AUTOGENERATED_COMMENT . '

require_once __DIR__ . "/vendor/autoload.php";

' . implode('
', array_map(function (string $name, $value) : string {
                return '$' . $name . ' = ' . json_encode($value) . ';';
            }, array_keys($plugins_vars), $plugins_vars)) . '
');

        file_put_contents(self::$plugin_root . "/" . self::PLUGIN_XML, '<?php xml version = "1.0" encoding = "UTF-8"?>
<!-- ' . htmlspecialchars(self::AUTOGENERATED_COMMENT) . ' -->
<plugin id="' . htmlspecialchars(strval($plugin_composer_json->ilias_plugin->id)) . '">
	' . (!empty($plugin_composer_json->ilias_plugin->events) ? '<events>
		' . implode('
		', array_map(function (stdClass $event) : string {
                    return '<event id="' . htmlspecialchars($event->id) . '" type="' . htmlspecialchars($event->type) . '" />';
                }, (array) $plugin_composer_json->ilias_plugin->events)) . '
	</events>' : '') . '
</plugin>
');

        if ($plugin_composer_json->ilias_plugin->slot === self::REPOSITORY_OBJECT) {
            if (!empty($plugin_composer_json->ilias_plugin->lucene_search)) {
                file_put_contents(self::$plugin_root . "/" . self::LUCENE_OBJECT_DEFINITION_XML, '<?xml version="1.0" encoding="UTF-8"?>
<!-- ' . htmlspecialchars(self::AUTOGENERATED_COMMENT) . ' -->
<ObjectDefinition xmlns:xi="http://www.w3.org/2001/XInclude" type="' . htmlspecialchars(strval($plugin_composer_json->ilias_plugin->id)) . '">
	<Document type="default">
		<xi:include href="../../../../../../../Services/Object/LuceneDataSource.xml" />
	</Document>
</ObjectDefinition>
');
            }
        }
    }
}
